services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=tpfapi
    volumes:
      - polls_pg_data:/postgres

volumes:
  polls_pg_data:
